version: '3.8'

services:
  api:
    build: ./api
    # command: gunicorn app:app --bind 0.0.0.0:5000
    command: /usr/bin/supervisord
    volumes:
      - ./api:/app
    restart: always
    env_file:
      - ./api/.env.dev
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db

  worker:
    build: ./worker
    volumes:
      - ./worker:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - redis
    cpus: "3.0"

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  db:
    build: ./db
    env_file:
      - ./db/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  node_modules:
  postgres_data:
  redis_data:
    driver: local