version: '3.8'

services:
  api:
    build: ./api
    restart: always
    command: python run.py
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - "5000:5000"
    env_file:
      - ./api/.env.dev
    depends_on:
      - redis
      - db

  celery:
    build:
        context: ./api
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env.dev
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  db:
    build: ./db
    env_file:
      - ./db/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
    driver: local