version: '3.8'

services:
  api:
    build: ./api
    # command: gunicorn app:app --bind 0.0.0.0:5000
    command: python run.py
    volumes:
      - ./api:/app
    restart: always
    env_file:
      - ./api/.env.dev
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db

  celery:
    build: ./api
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env.dev
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  db:
    build: ./db
    env_file:
      - ./db/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
    driver: local